import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { TrustProxy } from './trust-proxy.js';

/**
 * Validated environment — guardrail 7 (PLAN.md §2.1, §8.7).
 *
 * The rest of the workspace is forbidden by lint from touching `process.env`.
 * Everything arrives through this schema, so a missing or malformed variable
 * fails at BOOT with a message naming the variable, rather than surfacing as
 * `undefined` inside a request handler three weeks later — which is how a
 * misconfigured signing key becomes an authentication bypass instead of a crash.
 */

const NonEmpty = z.string().min(1);

/** 32 bytes, base64. Rejecting a short key here beats an AES error at runtime. */
const Base64Key = z.string().refine(
  (value) => {
    try {
      return Buffer.from(value, 'base64').length === 32;
    } catch {
      return false;
    }
  },
  { message: 'must be 32 bytes of base64-encoded key material' },
);

export const EnvSchema = z
  .object({
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    LOG_LEVEL: z.enum(['trace', 'debug', 'info', 'warn', 'error', 'fatal']).default('info'),

    /* Two URLs, never one. taskflow_app cannot bypass RLS and has no DDL
       rights; collapsing them would hand the runtime role the ability to drop
       its own RLS policies (§8.3). */
    DATABASE_URL: NonEmpty,
    DATABASE_POOL_MAX: z.coerce.number().int().positive().max(100).default(10),

    /* A THIRD role, for the audit projection (§8.6). taskflow_audit holds
       INSERT and SELECT on audit.audit_log and no UPDATE or DELETE anywhere, so
       the compliance record cannot be rewritten even by the process that writes
       it.

       Optional, and the consequence of omitting it is deliberately loud rather
       than silent: `withAuditScope` throws instead of falling back to the
       application role, which could not write an audit entry anyway. An API
       instance that only serves requests does not need it; the one running the
       outbox relay does. */
    DATABASE_AUDIT_URL: NonEmpty.optional(),

    /* A FIFTH role, for the backlinks relay (Phase 6 Wave 3, ai/phase-6-docs.md
       §3.10; migration 0025's own header). taskflow_backlinks holds only a
       COLUMN-LEVEL grant on docs.page_versions — id/org_id/page_id/created_at,
       never state — so this role can discover which pages changed and can
       never read a byte of what changed.

       Optional, matching DATABASE_AUDIT_URL's own reasoning exactly: an API
       instance that only serves requests does not need it; the one running
       the relay does, and `withBacklinksScope` throws rather than silently
       falling back to the application role, which cannot see across every
       tenant's page_versions in one claim. */
    DATABASE_BACKLINKS_URL: NonEmpty.optional(),

    /* A SIXTH role, for the due-reminder sweep (Phase 9 Wave 2,
       ai/phase-9-notifications.md §3.8; migration 0029's own header).
       taskflow_notification_sweep holds a COLUMN-LEVEL grant on work.cards
       — id/org_id/board_id/title/number/due_date/assignee_ids, nothing else
       — so this role can discover which cards are due and can never read a
       card's description or rank. Optional, matching DATABASE_BACKLINKS_URL:
       an instance that only serves requests does not need it; the one
       running the sweep does, and `withSweepScope` throws rather than
       silently falling back to the application role, which cannot see across
       every tenant's cards in one scan. */
    DATABASE_NOTIFICATION_SWEEP_URL: NonEmpty.optional(),

    /* Web Push (Phase 9 Wave 2, ai/phase-9-notifications.md §3.7). VAPID
       identifies the application server to the push service: a mailto: URL
       as the subject, and a P-256 key pair generated by
       `@taskflow/security`'s `generateVapidKeys`. Optional, unlike MAIL_HOST:
       an instance with no keys is a valid deployment that simply does not
       send push — the preferences UI reports that honestly instead of
       pretending the channel works. The private key is signing material and
       never leaves the server. */
    VAPID_SUBJECT: NonEmpty.optional(),
    VAPID_PUBLIC_KEY: NonEmpty.optional(),
    VAPID_PRIVATE_KEY: NonEmpty.optional(),

    MASTER_KEY_ID: NonEmpty,
    MASTER_KEY_BASE64: Base64Key,
    JWT_SECRET: Base64Key,

    /* Mail (§8.1). Mailpit locally, a real provider in deployed environments.
       Verification and reset links are the credential for the flow that issues
       them, so delivery is not a "nice to have" that can be stubbed out — an
       unset MAIL_HOST must fail at boot, not at the first signup. */
    MAIL_HOST: NonEmpty,
    MAIL_PORT: z.coerce.number().int().positive().max(65_535).default(1025),
    MAIL_SECURE: z
      .enum(['true', 'false'])
      .default('false')
      .transform((value) => value === 'true'),
    MAIL_FROM: NonEmpty,

    /* Object storage (§5, §8.4). MinIO locally, Cloudflare R2 on the free tier,
       S3 past 10 GB — all three speak the same API, so only these values
       change.

       Required rather than optional, for the same reason as MAIL_HOST: an
       attachment upload that fails at presign time because a bucket name was
       never set is a broken feature discovered by a user, where an unset
       variable is a boot failure discovered by whoever deployed it. */
    STORAGE_ENDPOINT: NonEmpty,
    STORAGE_REGION: z.string().default('us-east-1'),
    STORAGE_ACCESS_KEY_ID: NonEmpty,
    STORAGE_SECRET_ACCESS_KEY: NonEmpty,
    STORAGE_BUCKET_ATTACHMENTS: NonEmpty,
    STORAGE_BUCKET_EXPORTS: NonEmpty,
    /* Path-style addressing. Required by MinIO, which has no per-bucket DNS;
       R2 and S3 accept either. Defaults to true because the local stack is the
       one a developer runs without setting anything. */
    STORAGE_FORCE_PATH_STYLE: z
      .enum(['true', 'false'])
      .default('true')
      .transform((value) => value === 'true'),

    /* Largest attachment accepted, in bytes. Pinned into the upload signature
       and used as the ceiling on the server-side read during scanning, so it
       bounds memory as well as storage. */
    STORAGE_MAX_UPLOAD_BYTES: z.coerce
      .number()
      .int()
      .positive()
      .max(500 * 1024 * 1024)
      .default(25 * 1024 * 1024),

    /* Virus scanning (§8.4). An attachment is not downloadable until clamd has
       looked at it, and an unreachable scanner fails CLOSED — so these being
       wrong makes uploads stop working, which is the correct direction for a
       misconfiguration to fail in. */
    CLAMAV_HOST: z.string().default('localhost'),
    CLAMAV_PORT: z.coerce.number().int().positive().max(65_535).default(3310),

    API_PORT: z.coerce.number().int().positive().max(65_535).default(3000),
    API_HOST: z.string().default('0.0.0.0'),
    API_TRUST_PROXY: TrustProxy,

    /**
     * Whether THIS instance runs the chat retention sweep (Wave 4, §3.7).
     *
     * Off by default, and the default is the safe one. The sweep has no
     * SKIP-LOCKED claim, so two instances ticking together both issue the same
     * DELETE — the second removes nothing but still emits a batch of
     * `message.deleted` events, putting duplicate deletions in the compliance
     * record. Exactly one instance should enable it, until pg-boss provides a
     * schedule with a real lock.
     *
     * Parsed from the string 'true' rather than with `z.coerce.boolean()`,
     * which is a trap here: it treats EVERY non-empty string as true, so
     * `RETENTION_SWEEP_ENABLED=false` would enable the sweep. For a flag that
     * gates deleting user data, that failure runs the wrong way.
     */
    RETENTION_SWEEP_ENABLED: z
      .enum(['true', 'false'])
      .default('false')
      .transform((value) => value === 'true'),

    WEB_ORIGIN: z.string().url(),
  })
  /* NOT `.strict()`, unlike every other schema in this codebase.

     `process.env` carries a few hundred variables belonging to the OS, the
     shell, and whatever launched the process. Rejecting unknown keys here means
     the API cannot start on any real machine — which is exactly what happened
     the first time this was booted, after a unit test suite that fed it a tidy
     fixture object had passed. The typo protection that `.strict()` was reaching
     for is provided by `assertNoMisspelledVariables` below, which knows which
     names are ours. */
  .superRefine((env, ctx) => {
    if (env.NODE_ENV === 'production' && env.MASTER_KEY_BASE64 === env.JWT_SECRET) {
      // Reusing one secret for two purposes means compromising either
      // compromises both, and key rotation stops being independent.
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'MASTER_KEY_BASE64 and JWT_SECRET must be different values.',
      });
    }
  });

export type Env = z.infer<typeof EnvSchema>;

/**
 * Every TaskFlow environment variable, across ALL services — not just the ones
 * this app reads.
 *
 * Kept in sync with .env.example. The API does not consume the storage or mail
 * settings, but they are legitimately present in a developer's environment, so
 * the misspelling check has to know about them or it would reject a correct
 * setup.
 */
const KNOWN_VARIABLES = new Set([
  'NODE_ENV',
  'LOG_LEVEL',
  'DATABASE_URL',
  'DATABASE_MIGRATION_URL',
  'DATABASE_AUDIT_URL',
  'DATABASE_BACKLINKS_URL',
  'DATABASE_NOTIFICATION_SWEEP_URL',
  'VAPID_SUBJECT',
  'VAPID_PUBLIC_KEY',
  'VAPID_PRIVATE_KEY',
  /* apps/realtime's own consumer role (Phase 4 §3.5). Listed here — as the
     comment above this set explains — because a developer's environment
     legitimately carries variables this app does not read, and the misspelling
     check would otherwise reject a correct setup. */
  'DATABASE_REALTIME_URL',
  /* apps/collab's write-exception role (Phase 6 Wave 2, migration 0024). Same
     reasoning as DATABASE_REALTIME_URL: it is in .env.example, this app does
     not read it, and an unlisted one makes the API refuse to boot over a
     correctly-spelled variable the moment a developer copies the example. */
  'DATABASE_COLLAB_URL',
  'DATABASE_POOL_MAX',
  'STORAGE_ENDPOINT',
  'STORAGE_REGION',
  'STORAGE_ACCESS_KEY_ID',
  'STORAGE_SECRET_ACCESS_KEY',
  'STORAGE_BUCKET_ATTACHMENTS',
  'STORAGE_BUCKET_EXPORTS',
  'STORAGE_FORCE_PATH_STYLE',
  'STORAGE_MAX_UPLOAD_BYTES',
  'CLAMAV_HOST',
  'CLAMAV_PORT',
  'MAIL_HOST',
  'MAIL_PORT',
  'MAIL_SECURE',
  'MAIL_FROM',
  'MASTER_KEY_ID',
  'MASTER_KEY_BASE64',
  'JWT_SECRET',
  'API_PORT',
  'API_HOST',
  'API_TRUST_PROXY',
  'RETENTION_SWEEP_ENABLED',
  'WEB_ORIGIN',
  /* Read by apps/web's vite.config.ts, never by a server — but they carry the
     `WEB_` prefix, so `assertNoMisspelledVariables` treats them as ours and
     REJECTS them unless they are listed here. A developer who set either one in
     .env to point the dev server at a non-default backend would find both the
     API and the gateway refusing to boot, with an error naming a variable that
     is spelled perfectly correctly. */
  'WEB_API_ORIGIN',
  'WEB_REALTIME_ORIGIN',
  /* Read by apps/web's vite.config.ts for its /collab proxy target. Same
     class as the two above: `WEB_` prefix, never read by a server, must be
     listed or it is rejected. */
  'WEB_COLLAB_ORIGIN',
  /* Read by apps/web's vite.config.ts for `server.allowedHosts` — the hosts
     the dev server accepts besides localhost (tunnels such as ngrok). Same
     class as the three above: `WEB_` prefix, never read by a server, must
     be listed or it is rejected. */
  'WEB_ALLOWED_HOSTS',
  /* apps/realtime (Phase 4). Same reasoning as DATABASE_REALTIME_URL above —
     this set is every TaskFlow variable across ALL services, not the ones this
     app reads, so that a typo is caught wherever it is made. */
  'REALTIME_PORT',
  'REALTIME_HOST',
  'REALTIME_TRUST_PROXY',
  'REALTIME_REAUTH_LEAD_SECONDS',
  'REALTIME_POLL_INTERVAL_MS',
  'REALTIME_MAX_CONNECTIONS_PER_IP_PER_MINUTE',
  'REALTIME_MAX_JOINS_PER_MINUTE',
  'REALTIME_MAX_REFUSED_JOINS_PER_MINUTE',
]);

/**
 * Prefixes that mark a variable as ours.
 *
 * Deliberately excludes `NODE_` and `LOG_`, which collide with tooling that has
 * nothing to do with this project.
 */
const TASKFLOW_PREFIXES = [
  'DATABASE_',
  'STORAGE_',
  'MAIL_',
  'MASTER_KEY',
  'JWT_',
  'API_',
  'WEB_',
  'CLAMAV_',
  'REALTIME_',
];

/**
 * Rejects a variable that looks like ours but is not one of ours.
 *
 * The failure being prevented: `MASTER_KEY_BASE_64` set instead of
 * `MASTER_KEY_BASE64`. Zod would report the real name as missing, which is
 * already a decent error, but naming the near-miss turns a five-minute stare
 * into a one-line fix.
 *
 * Scoped to our own prefixes rather than to everything, because "everything"
 * includes the operating system.
 */
function assertNoMisspelledVariables(source: Record<string, string | undefined>): void {
  const suspects = Object.keys(source).filter(
    (key) =>
      !KNOWN_VARIABLES.has(key) && TASKFLOW_PREFIXES.some((prefix) => key.startsWith(prefix)),
  );

  if (suspects.length > 0) {
    throw new Error(
      `Unrecognized TaskFlow environment variable(s): ${suspects.join(', ')}.\n` +
        'Check the spelling against .env.example — a near-miss name means the real\n' +
        'variable is unset and something is running on a default it should not be.',
    );
  }
}

/**
 * Parses an environment source. Takes the source as an argument so tests do not
 * have to mutate the real `process.env` and leak state between files.
 */
export function parseEnv(source: Record<string, string | undefined>): Env {
  assertNoMisspelledVariables(source);
  const result = EnvSchema.safeParse(source);

  if (!result.success) {
    const detail = result.error.issues
      .map((issue) => `  ${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n');

    throw new Error(`Invalid environment:\n${detail}`);
  }
  return result.data;
}

/**
 * Reads the real environment, loading a repo-root `.env` first if one exists.
 *
 * Lives here rather than in `main.ts` because this module is the one place
 * permitted to touch `process.env` — the guardrail that enforces that is the
 * reason a validated config exists at all, and routing the process entry point
 * around it would be the first crack.
 *
 * `loadEnvFile` follows `--env-file` semantics and does NOT overwrite variables
 * that are already set, so injected production secrets always beat a file that
 * happens to be on disk.
 */
export function loadEnv(): Env {
  const here = dirname(fileURLToPath(import.meta.url));
  const envFile = resolve(here, '..', '..', '..', '..', '.env');

  if (existsSync(envFile)) {
    process.loadEnvFile(envFile);
  }
  return parseEnv(process.env);
}
