import type { Wire } from '@taskflow/client';
import type { MobileTRPCClient } from './trpc-client.js';

/**
 * Docs (Phase 6) — spaces and the page tree, plus the pure logic every
 * other Docs lib file needs (`buildPageTree`, `descendantIdsOf`). No
 * `react-native` import anywhere in this file, the same split every other
 * feature's lib file establishes.
 *
 * **Reading/writing a page's actual content is split, and only half of
 * that half is possible on this platform.** `use-doc-page.ts`/
 * `docs-collab.ts` are the live Yjs client this pass added — a page's real
 * content only ever exists as a live document synced over `apps/collab`'s
 * Hocuspocus WebSocket protocol, there is no `pages.getContent`-style REST
 * route (`pages.list` returns tree metadata only). Reading is real;
 * WRITING is not, and cannot be without a from-scratch rich-text INPUT
 * component — ProseMirror (what `apps/web`'s editor is built on) needs a
 * DOM, and React Native has none. That is a hard platform constraint, not
 * a scope choice, and it is what actually gates everything else below:
 * every Docs capability that needs the client to COMPOSE rich text or
 * select a text range is out of reach until that component exists.
 *
 * **Comments and suggestions**: `docs-comments.ts`/`docs-suggestions.ts`.
 * Listing, resolving, editing/deleting one's own, and — for suggestions —
 * accepting/rejecting/withdrawing ("deciding") are all fully portable: a
 * suggestion's `decide` is a pure server-side status flip even on web, per
 * `suggestion.service.ts`'s own header, so it needs nothing this app
 * lacks. CREATING one needs an anchor — a Yjs `RelativePosition` naming
 * where in the document it applies — which web builds from a live
 * ProseMirror selection. This app has no selection to convert, so
 * `docs-collab.ts`'s `pageStartAnchor` anchors every mobile-created
 * comment/suggestion to the PAGE itself (a fixed, collapsed point at the
 * document's start) rather than to a phrase in it. The server cannot tell
 * the difference — `decodeAnchor` only checks the bytes are a well-formed
 * relative position, never what they name.
 *
 * **Backlinks, publish/unpublish, PDF export, and templates are all fully
 * portable, and none of them need the anchor workaround above** — none of
 * the four ever sends or receives rich text from the client at all.
 * Backlinks (`docs.backlinks.list`) is a plain read, computed entirely
 * server-side. Publish/unpublish are one-shot `{ pageId }` mutations; the
 * server materializes the version to publish, this app never does.
 * `docs.pages.exportPdf` returns whole base64 PDF bytes generated by
 * `pdf-lib` (pure JS, no headless browser) from the server's own last
 * saved version — `pdf-save.ts` is the one genuinely new mobile-native
 * piece, writing those bytes to disk and handing them to the OS share
 * sheet, the native equivalent of web's Blob-download trick.
 * `docs.templates.createPage` copies a stored Yjs snapshot entirely
 * server-side from a `templateId` this app only ever forwards, never reads.
 */

export type Space = Wire<
  Awaited<ReturnType<MobileTRPCClient['docs']['spaces']['list']['query']>>
>[number];

export type Page = Wire<
  Awaited<ReturnType<MobileTRPCClient['docs']['pages']['list']['query']>>
>[number];

export const SPACES_QUERY_KEY = ['docs.spaces.list'] as const;

export function pagesQueryKey(spaceId: string): readonly ['docs.pages.list', string] {
  return ['docs.pages.list', spaceId];
}

export type Backlink = Wire<
  Awaited<ReturnType<MobileTRPCClient['docs']['backlinks']['list']['query']>>
>[number];

export function backlinksQueryKey(pageId: string): readonly ['docs.backlinks.list', string] {
  return ['docs.backlinks.list', pageId];
}

/** One page, positioned in the tree — `depth` is how deeply nested it is
 *  (0 = top level), which is what a flat `FlatList` needs to render
 *  indentation without recursion. */
export interface PageTreeRow {
  readonly page: Page;
  readonly depth: number;
}

/**
 * Flattens `docs.pages.list`'s flat, parent-pointer rows into a
 * depth-annotated, rank-ordered list a `FlatList` can render directly —
 * the mobile equivalent of the recursive tree component web's page-tree
 * sidebar renders, since a `FlatList` has no native concept of nested
 * children.
 *
 * Ordering is `rank` — the same base62 scheme `packages/contracts/rank.ts`
 * uses for Work cards, lexicographically comparable as plain strings — so
 * siblings sort correctly without any numeric parsing.
 */
export function buildPageTree(pages: readonly Page[]): readonly PageTreeRow[] {
  const byParent = new Map<string | null, Page[]>();
  for (const page of pages) {
    const bucket = byParent.get(page.parentPageId);
    if (bucket) {
      bucket.push(page);
    } else {
      byParent.set(page.parentPageId, [page]);
    }
  }
  for (const bucket of byParent.values()) {
    bucket.sort((a, b) => (a.rank < b.rank ? -1 : a.rank > b.rank ? 1 : 0));
  }

  const rows: PageTreeRow[] = [];
  const visit = (parentId: string | null, depth: number): void => {
    for (const page of byParent.get(parentId) ?? []) {
      rows.push({ page, depth });
      visit(page.pageId, depth + 1);
    }
  };
  visit(null, 0);
  return rows;
}

/** This page and every one of its descendants, by id — what a "move"
 *  picker must exclude from its target list, since setting a page's own
 *  descendant as its new parent would create a cycle. The server would
 *  refuse this anyway, but a picker that never offers it is a better
 *  experience than one that offers it and then explains why not. */
export function descendantIdsOf(pages: readonly Page[], pageId: string): ReadonlySet<string> {
  const children = new Map<string | null, string[]>();
  for (const page of pages) {
    const bucket = children.get(page.parentPageId);
    if (bucket) {
      bucket.push(page.pageId);
    } else {
      children.set(page.parentPageId, [page.pageId]);
    }
  }

  const found = new Set<string>([pageId]);
  const stack = [pageId];
  while (stack.length > 0) {
    const current = stack.pop();
    if (current === undefined) continue;
    for (const childId of children.get(current) ?? []) {
      if (found.has(childId)) continue;
      found.add(childId);
      stack.push(childId);
    }
  }
  found.delete(pageId);
  return found;
}
