import { unsafeAsId, type RequestId } from '@taskflow/contracts';
import type { EventContext } from '@taskflow/events';

/**
 * Small shared helpers.
 *
 * Time first, because every module needs it and every module needs the SAME
 * one: seeded rows must be consistent with each other — a comment cannot predate
 * its card, a `done_at` cannot predate the item it ticks — and that only holds
 * if every offset is measured from `ctx.now` rather than from whenever a module
 * happened to run.
 */

/**
 * The request id every seeded event carries.
 *
 * Real events carry the id of the HTTP request that caused them. Seeded rows had
 * no request, and minting a plausible-looking one per event would make the audit
 * log assert that a call happened. One obviously synthetic constant is honest,
 * and it doubles as a marker: grepping the audit log for it returns exactly the
 * entries this seeder produced.
 */
export const SEED_REQUEST_ID: RequestId = unsafeAsId<'RequestId'>(
  '00000000-0000-7000-8000-00005eed0000',
);

/**
 * The envelope for a seeded event.
 *
 * Wraps the three `unsafeAsId` calls every emission needs. They are legitimate
 * here — these ids were generated by this process a few lines earlier, so there
 * is nothing to re-validate — but they should appear in one place rather than
 * forty, so that grepping for the unsafe path finds a single reviewed helper.
 */
export function envelopeFor(orgId: string, actorId: string | null, occurredAt: Date): EventContext {
  return {
    orgId: unsafeAsId<'OrgId'>(orgId),
    actorId: actorId === null ? null : unsafeAsId<'UserId'>(actorId),
    requestId: SEED_REQUEST_ID,
    occurredAt,
  };
}

const MS_PER_DAY = 24 * 60 * 60 * 1000;
const MS_PER_MINUTE = 60 * 1000;

export function daysBefore(reference: Date, days: number): Date {
  return new Date(reference.getTime() - days * MS_PER_DAY);
}

export function daysAfter(reference: Date, days: number): Date {
  return new Date(reference.getTime() + days * MS_PER_DAY);
}

export function minutesAfter(reference: Date, minutes: number): Date {
  return new Date(reference.getTime() + minutes * MS_PER_MINUTE);
}

/** The later of two instants. Keeps `updated_at >= created_at` honest. */
export function latest(a: Date, b: Date): Date {
  return a.getTime() >= b.getTime() ? a : b;
}

/**
 * A URL-safe slug.
 *
 * `teams_org_slug_key` and `orgs_slug_key` are unique indexes, so a collision is
 * a failed run rather than a cosmetic problem. Callers that generate slugs from
 * a corpus disambiguate with an index.
 */
export function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}
