-- 0004 — tenancy: organizations, memberships, teams (PLAN.md §7, §8.2, §8.3)
--
-- This is the migration that makes `app.org_id` mean something. Until now the
-- RLS machinery existed and no table used it; from here every tenant table
-- carries the policy and the application role cannot bypass it.
--
-- Three things in this file are worth reading before changing anything.
--
-- 1. THE TENANT COLUMN ON identity.orgs IS `id`, NOT `org_id`.
--    An organization IS the tenant, so a separate org_id column would duplicate
--    the primary key and create a way for the two to disagree. The policy is
--    generated by tenantRlsPolicy(..., { column: 'id' }) so the predicate stays
--    identical in every other respect.
--
-- 2. CREATING AN ORG NEEDS NO PRIVILEGED PATH.
--    WITH CHECK means an INSERT into identity.orgs must satisfy
--    `id = app.org_id`, which reads like a chicken-and-egg problem: you cannot
--    scope to an org that does not exist. It is not one. Ids are UUIDv7
--    generated by the application (§7.1), so the service mints the id, opens
--    withOrgScope(newOrgId), and inserts the org and its owner membership in
--    that one transaction. Every write in the system stays scoped, and there is
--    no escape hatch for a later mistake to reach for.
--
-- 3. TWO POLICIES CONSULT `app.user_id`, AND BOTH ARE FOR SELECT.
--    See the block above them. The short version: the org switcher has to read
--    across orgs, and a WITH CHECK on user_id would turn that read convenience
--    into self-service admission to any tenant.

-- --------------------------------------------------------------------------
-- Organizations
-- --------------------------------------------------------------------------
CREATE TABLE identity.orgs (
  id          uuid        PRIMARY KEY,

  name        text        NOT NULL,

  -- URL-facing identifier. Unique globally, unlike every other name in the
  -- system, because it appears in paths and in email — two places where a
  -- collision between tenants is user-visible.
  slug        text        NOT NULL,

  status      text        NOT NULL DEFAULT 'active',

  -- Soft delete (§7.1). Distinct from erasure: purging is a retention job, and
  -- GDPR erasure destroys the org's data key rather than chasing rows (§8.4).
  deleted_at  timestamptz,

  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT orgs_status_valid CHECK (status IN ('active', 'suspended', 'deleted')),
  CONSTRAINT orgs_slug_format  CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])$'),
  CONSTRAINT orgs_name_present CHECK (length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX orgs_slug_key ON identity.orgs (slug);

-- --------------------------------------------------------------------------
-- Memberships — the join between a user and an organization, and the ONLY
-- place a role is stored.
--
-- Deliberately not a column on users and not a claim in the access token. A
-- token claim would mean the caller's own credential asserted their role, so a
-- demotion would not take effect until the token expired — precisely the ten
-- minutes that matter most. Every request reads this table instead.
-- --------------------------------------------------------------------------
CREATE TABLE identity.memberships (
  id          uuid        PRIMARY KEY,
  org_id      uuid        NOT NULL REFERENCES identity.orgs (id)  ON DELETE CASCADE,
  user_id     uuid        NOT NULL REFERENCES identity.users (id) ON DELETE CASCADE,

  -- Mirrors ROLES in packages/policy. The CHECK is a second copy of that list
  -- and could drift from it, so packages/db asserts the two agree — a role the
  -- policy engine has never heard of denies everything (see decide.ts), which
  -- is safe but silent, and silent is the failure worth a test.
  role        text        NOT NULL,

  status      text        NOT NULL DEFAULT 'active',

  -- Who issued the invitation. Nullable: the founding owner invited nobody.
  invited_by  uuid        REFERENCES identity.users (id) ON DELETE SET NULL,
  joined_at   timestamptz NOT NULL DEFAULT now(),

  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT memberships_role_valid   CHECK (role   IN ('owner', 'admin', 'member', 'guest')),
  CONSTRAINT memberships_status_valid CHECK (status IN ('active', 'suspended'))
);

-- One membership per user per org. The unique index is the thing that makes a
-- concurrent double-invite resolve to one row rather than two rows with
-- different roles, which would make `can()` depend on which one was read first.
CREATE UNIQUE INDEX memberships_org_user_key ON identity.memberships (org_id, user_id);

-- The org switcher's query: every org this user belongs to.
CREATE INDEX memberships_user_idx ON identity.memberships (user_id) WHERE status = 'active';

-- --------------------------------------------------------------------------
-- Teams
--
-- A named group inside one org. Teams matter to authorization because a
-- relationship tuple may name a team as its subject (0005), which is how "the
-- platform team owns this project" is expressed without a role explosion.
-- --------------------------------------------------------------------------
CREATE TABLE identity.teams (
  id          uuid        PRIMARY KEY,
  org_id      uuid        NOT NULL REFERENCES identity.orgs (id) ON DELETE CASCADE,

  name        text        NOT NULL,
  slug        text        NOT NULL,

  archived_at timestamptz,

  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT teams_slug_format  CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$'),
  CONSTRAINT teams_name_present CHECK (length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX teams_org_slug_key ON identity.teams (org_id, slug);

-- Referenced by the composite foreign key on team_members below. A plain
-- REFERENCES teams(id) would let a row claim a team from another org while
-- carrying this org's org_id, which RLS would happily show to the wrong tenant.
CREATE UNIQUE INDEX teams_org_id_key ON identity.teams (org_id, id);

CREATE TABLE identity.team_members (
  -- Denormalized from teams, because RLS filters on a column of THIS table.
  -- Joining to teams for the predicate would make the policy depend on another
  -- table's policy, which is both slower and a recursion hazard. The composite
  -- FK below is what keeps the copy honest.
  org_id   uuid        NOT NULL,
  team_id  uuid        NOT NULL,
  user_id  uuid        NOT NULL REFERENCES identity.users (id) ON DELETE CASCADE,

  added_at timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (team_id, user_id),

  CONSTRAINT team_members_team_fk
    FOREIGN KEY (org_id, team_id) REFERENCES identity.teams (org_id, id) ON DELETE CASCADE
);

-- The tuple loader's query: every team this user is in, to expand team-subject
-- tuples into user-subject ones before the policy engine sees them.
CREATE INDEX team_members_user_idx ON identity.team_members (org_id, user_id);

-- --------------------------------------------------------------------------
-- Row-Level Security (§8.3)
--
-- Generated form, repeated verbatim from packages/db/src/rls.ts. FORCE is what
-- makes it apply to the table owner (taskflow_migrator) as well; ENABLE alone
-- protects nothing from the role that ran this file.
-- --------------------------------------------------------------------------

ALTER TABLE identity.orgs ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.orgs FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS orgs_tenant_isolation ON identity.orgs;
CREATE POLICY orgs_tenant_isolation ON identity.orgs
  USING (id = NULLIF(current_setting('app.org_id', true), '')::uuid)
  WITH CHECK (id = NULLIF(current_setting('app.org_id', true), '')::uuid);

ALTER TABLE identity.memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.memberships FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS memberships_tenant_isolation ON identity.memberships;
CREATE POLICY memberships_tenant_isolation ON identity.memberships
  USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
  WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);

ALTER TABLE identity.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.teams FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS teams_tenant_isolation ON identity.teams;
CREATE POLICY teams_tenant_isolation ON identity.teams
  USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
  WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);

ALTER TABLE identity.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE identity.team_members FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS team_members_tenant_isolation ON identity.team_members;
CREATE POLICY team_members_tenant_isolation ON identity.team_members
  USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
  WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);

-- --------------------------------------------------------------------------
-- The self-read policies (§8.3)
--
-- These are the only two policies in the system that consult `app.user_id`, and
-- they exist for one question: "which organizations am I a member of?" The org
-- switcher must answer it before an org is selected, so no value of
-- `app.org_id` is the right one.
--
-- Both are FOR SELECT, with no WITH CHECK, and that restriction is the whole
-- safety argument. A permissive WITH CHECK on `user_id` would let any
-- authenticated caller INSERT a membership row naming themselves in any
-- organization — self-service admission to every tenant, arriving as a
-- convenience for a read.
--
-- Permissive policies are OR'ed, so these WIDEN what is visible whenever
-- `app.user_id` is set. That is why withOrgScope clears it and withUserScope
-- clears `app.org_id`: each scope sets both variables, so neither can be
-- inherited from an earlier transaction on the same pooled connection.
-- --------------------------------------------------------------------------

DROP POLICY IF EXISTS memberships_self_read ON identity.memberships;
CREATE POLICY memberships_self_read ON identity.memberships
  FOR SELECT
  USING (user_id = NULLIF(current_setting('app.user_id', true), '')::uuid);

-- Reads memberships, whose own policies apply in turn. That terminates because
-- nothing in memberships' policies refers back to orgs; a policy pair that
-- referenced each other would recurse, and Postgres reports that at query time
-- rather than here.
DROP POLICY IF EXISTS orgs_self_read ON identity.orgs;
CREATE POLICY orgs_self_read ON identity.orgs
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
        FROM identity.memberships m
       WHERE m.org_id = identity.orgs.id
         AND m.status = 'active'
         AND m.user_id = NULLIF(current_setting('app.user_id', true), '')::uuid
    )
  );
