-- 0045 — the search projection and its claim role (ai/phase-8-search.md §2)
--
-- Phase 8 Wave 2: `search.documents` is the projection the outbox search
-- consumer writes and the search route reads — a single org-scoped table that
-- lets one query span cards, messages, pages and comments without joining four
-- heterogeneous tables, exactly the shape the audit and notification
-- projections already established for their own consumers (§2.1).
--
-- ==========================================================================
-- A NEW SCHEMA, AND DELIBERATELY NO `ALTER DEFAULT PRIVILEGES` ON IT
-- ==========================================================================
--
-- 0001_schemas pairs every schema it creates with ALTER DEFAULT PRIVILEGES
-- granting taskflow_app full CRUD on every table a later migration creates
-- there. That is convenient and it has the failure mode migration 0036 had to
-- correct (and 0041 restated): a migration that says "SELECT only" on a table
-- in such a schema is weaker than what the database already enforces. With no
-- default privileges here, every grant is explicit forever — the same decision
-- 0041 made for the rtc schema, applied to a schema whose one table is written
-- by a background consumer and read by a route, where it matters just as much
-- that "nothing may DROP search.documents" is a fact rather than an intention.

CREATE SCHEMA IF NOT EXISTS search;

GRANT USAGE ON SCHEMA search TO taskflow_app;

-- --------------------------------------------------------------------------
-- search.documents — the projection.
--
-- `id` is the projection row's own id (generated by the indexer); the
-- (org_id, entity_type, entity_id) triple is what a redelivered event upserts
-- against — the idempotency the at-least-once claim contract needs, the same
-- role `notifications_event_user_key` plays for the notification projection.
--
-- `entity_type` is a CHECK, not an enum, and closed to the four entity kinds
-- Wave 2 indexes. Transcripts join in Wave 3 by widening the CHECK the way
-- 0027 widened notifications' kind — one constraint swap, no enum ceremony.
--
-- `body` is the flattened searchable text (never TipTap JSON — the
-- description_text / body_text / excerpt columns the indexer reads already
-- exist precisely so search never parses a document). Wave 2 indexes page
-- TITLES only; page `body` stays NULL until the named follow-up that reuses
-- materializeCurrentState (§2.4). `archived` is a normalized boolean across
-- all four sources (cards archive via archived_at, messages via deleted_at,
-- channels via their own archived_at propagating to their message rows) so
-- one filter means the same thing for every entity type.
--
-- `metadata` carries the parent context the route needs for two things the
-- projection columns cannot answer: building each hit's permalink, and
-- resolving its resource Target for the per-hit can() check. For a card it is
-- { board_id, project_id }; for a message { channel_id }; for a page
-- { space_id }; for a comment { card_id, board_id } or { page_id }.
-- --------------------------------------------------------------------------
CREATE TABLE search.documents (
  id          uuid        PRIMARY KEY,
  org_id      uuid        NOT NULL REFERENCES identity.orgs (id) ON DELETE CASCADE,
  entity_type text        NOT NULL,
  entity_id   uuid        NOT NULL,
  title       text,
  body        text,
  author_id   uuid,
  updated_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL,
  archived    boolean     NOT NULL DEFAULT false,
  metadata    jsonb,
  CONSTRAINT documents_entity_type_check
    CHECK (entity_type IN ('card', 'message', 'page', 'comment')),
  CONSTRAINT documents_org_entity_key UNIQUE (org_id, entity_type, entity_id)
);

-- The route's per-hit can() loop loads one parent row per hit, keyed by
-- entity_id; org_id leads because every query is RLS-scoped to one org.
CREATE INDEX documents_entity_idx ON search.documents (org_id, entity_type, entity_id);

-- Full-text and trigram indexes over the concatenation the `text` field
-- compiles to (packages/filter/src/fields.ts — `text` covers title AND body,
-- so a page with no body is still findable by its title). The 'english'
-- argument is required: the single-argument to_tsvector depends on a session
-- GUC and is therefore not immutable, so it cannot be indexed — the identical
-- rule migration 0008 recorded for cards_search_idx. Both lead with org_id
-- per the RLS template; btree_gin (installed in 01-extensions.sql) is what
-- makes a scalar uuid column a legal GIN prefix.
CREATE INDEX documents_search_tsv_idx ON search.documents
  USING gin (org_id, to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, '')));

CREATE INDEX documents_search_trgm_idx ON search.documents
  USING gin (org_id, (coalesce(title, '') || ' ' || coalesce(body, '')) gin_trgm_ops);

-- --------------------------------------------------------------------------
-- Row-Level Security (§8.3)
--
-- Generated form, repeated verbatim from packages/db/src/rls.ts: FORCE is what
-- makes it apply to the table owner (taskflow_migrator) as well; NULLIF
-- collapses an unset app.org_id and an empty one to the same NULL, so a
-- scoping bug fails closed instead of raising 22P02. The app role is the only
-- reader AND writer (the indexer works under withOrgScope as taskflow_app —
-- the 0035 "one role, one job" shape — and the route reads the same way), so
-- one policy pair serves both.
-- --------------------------------------------------------------------------
ALTER TABLE search.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE search.documents FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS documents_tenant_isolation ON search.documents;
CREATE POLICY documents_tenant_isolation ON search.documents
  USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
  WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid);

-- Explicit, because this schema has no default privileges: taskflow_app holds
-- exactly what the projection's two surfaces need, and nothing it does not.
GRANT SELECT, INSERT, UPDATE, DELETE ON search.documents TO taskflow_app;

-- --------------------------------------------------------------------------
-- taskflow_search — the indexer's CLAIM role (0016's recipe)
-- --------------------------------------------------------------------------
-- The role itself is created in docker/postgres/init/02-roles.sql, not here —
-- roles are cluster-wide and migrations run as taskflow_migrator, which is
-- NOCREATEROLE on purpose (0016's own header says the same for
-- taskflow_realtime). A database whose volume predates that file fails this
-- migration with "role taskflow_search does not exist"; the fix is
-- `docker compose down -v && docker compose up -d`, not loosening the migrator.
--
-- What this role may do is deliberately tiny: CLAIM events from the outbox
-- under its own consumer name. It holds NOTHING on search.documents — the
-- actual indexing happens afterward, per event, under the ordinary
-- taskflow_app role inside withOrgScope, exactly the way taskflow_backlinks
-- claims page_versions and never reads `state` (migration 0025's header).
--
-- The consumer name needs no CHECK widening: outbox_dispatch's only CHECK
-- (0015) is `length(btrim(consumer)) > 0`, so 'search' is legal the moment a
-- policy names it — the spec's §2.3 assumption of an enum to widen was read
-- against the real migration before writing this one, per its own instruction.

GRANT USAGE ON SCHEMA platform TO taskflow_search;

-- Reading the queue. Mirrors outbox_relay_read (0006) / outbox_realtime_read
-- (0016) rather than widening either: three policies scoped to three roles
-- say "audit may read every org's events, and so may realtime, and so may
-- search" as three separately revocable answers.
GRANT SELECT, UPDATE ON platform.outbox TO taskflow_search;

DROP POLICY IF EXISTS outbox_search_read ON platform.outbox;
CREATE POLICY outbox_search_read ON platform.outbox
  FOR SELECT TO taskflow_search
  USING (true);

-- WITH CHECK (false), not (true), and the asymmetry is the whole point —
-- the identical comment 0016 writes for outbox_realtime_mark, reproduced
-- because it was verified against a real database the hard way: claimPending
-- claims with `SELECT ... FOR UPDATE OF o SKIP LOCKED`, and Postgres's RLS
-- for a LOCKING select requires a row to pass a policy applying to UPDATE.
-- WITHOUT this policy the claim silently returns zero rows, indistinguishable
-- from an idle queue. WITH CHECK (false) permits the lock — a locking select
-- never writes a row, so it never reaches WITH CHECK — and refuses an actual
-- write, because this role's bookkeeping lives in outbox_dispatch, never on
-- the outbox row itself.
DROP POLICY IF EXISTS outbox_search_mark ON platform.outbox;
CREATE POLICY outbox_search_mark ON platform.outbox
  FOR UPDATE TO taskflow_search
  USING (true)
  WITH CHECK (false);

-- Its own dispatch bookkeeping, pinned to its own consumer name. The WITH
-- CHECK is the control that keeps one consumer's typo from erasing another's
-- queue: an indexer that passed 'audit' to markDispatched would otherwise
-- delete an event from the AUDIT relay's claim, silently losing a compliance
-- entry to a string literal in a different app.
GRANT SELECT, INSERT, UPDATE ON platform.outbox_dispatch TO taskflow_search;

DROP POLICY IF EXISTS outbox_dispatch_search_read ON platform.outbox_dispatch;
CREATE POLICY outbox_dispatch_search_read ON platform.outbox_dispatch
  FOR SELECT TO taskflow_search
  USING (consumer = 'search');

DROP POLICY IF EXISTS outbox_dispatch_search_insert ON platform.outbox_dispatch;
CREATE POLICY outbox_dispatch_search_insert ON platform.outbox_dispatch
  FOR INSERT TO taskflow_search
  WITH CHECK (consumer = 'search');

DROP POLICY IF EXISTS outbox_dispatch_search_update ON platform.outbox_dispatch;
CREATE POLICY outbox_dispatch_search_update ON platform.outbox_dispatch
  FOR UPDATE TO taskflow_search
  USING (consumer = 'search')
  WITH CHECK (consumer = 'search');
